---
# Playbook Configure master Jenkins (Ubuntu 1604 / 1804)
- name: Install Jenkins
  hosts: "{{ jenkins_host }}"
  gather_facts: no
  become: yes  #sudo

  vars_files:
    - vars_vault_jn.yml

  vars_prompt:
    - name: "jenkins_host"
      prompt: "Enter hostname : "
      default: jenkins
      private: no
    - name: "jenkins_user"
      prompt: "Enter username for jenkins (jnadm) : "
      default: jenkins
      private: no


  tasks:
    - name: UPDATE (apt update -y)
      apt:
        update_cache: yes
      register: apt_update
    - debug: msg="{{ apt_update }}"

    - name: UPGRADE (apt upgrade -y)
      apt:
        upgrade: 'yes'
      register: apt_upgrade
    - debug: msg="{{ apt_upgrade }}"

    - name: Install packages  
      apt:
        name: '{{ item }}'
        state: latest
      loop:
      - python3-pip
      - zip
      - vim
      - mc
      - git
      - net-tools
      - openjdk-8-jre
      - gnupg
      - gnupg[12]

    - name: CREATE USERS for jenkins
      user:
        name: "{{ jenkins_user }}"
        password: "{{ password }}"
        #encrypt: "md5_crypt"
        shell: /bin/bash
        groups: root
        append: yes
        home: /home/{{ jenkins_user }}
        comment: jenkins administrator > "{{ jenkins_user }}"

    - name: CREATE FOLDER for Jenkins jobs
      file:
        path: "/usr/jenkins/"
        state: directory
        mode: 0777
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
    
    - name: CREATE FOLDER $HOME/.shh
      file:
        path: "/home/{{ jenkins_user }}/.ssh"
        state: directory
        mode: 0644
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        path: /home/{{ jenkins_user }}/.ssh/id_rsa
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0644

    - name: Fix owner of the generated pub key
      file:
        path: /home/{{ jenkins_user }}/.ssh/id_rsa.pub
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0640


    
    #- name: Copy file authorized_keys 
    #  copy:
    #    src: ~/pbcopy
    #    dest: ~/
    #    mode: 0640
    
