---
# Playbook PreInstall Slave jenkins on Ubuntu
- name: Install Jenkins
  hosts: "{{ jenkins_host }}"
  gather_facts: no
  become: yes  #sudo
  become_method: sudo

  vars_prompt:
    - name: "jenkins_host"
      prompt: "Enter hostname : "
      default: jenkins
      private: no

  tasks:
    - name: UPDATE (apt update -y)
      apt:
        update_cache: yes
      register: apt_update
    - debug: msg="{{ apt_update }}"

    - name: UPGRADE (apt upgrade -y)
      apt:
        upgrade: 'yes'
      register: apt_upgrade
    - debug: msg="{{ apt_upgrade }}"

    - name: Install packages  
      apt:
        name: '{{ item }}'
        state: latest
      loop:
      - python3-pip
      - zip
      - vim
      - mc
      - git
      - net-tools
      - openjdk-8-jre
      - gnupg
      - gnupg[12]

      


    - name: CREATE FOLDER for Jenkins jobs
      file:
        path: "/usr/jenkins/"
        state: directory
        mode: '0777'
    

  # add 
  # add user 
  # mkdir ~{{user}}/.ssh
  # echo "ssh-rsa in master jenkins"  ~{{user}}/.ssh/authorized_keys
  # add /etc/hosts ip ....


