---
- name: Add Repo witch ProxMox
  hosts: proxmox
  gather_facts: no
  become: yes  #sudo


  tasks:
    - name: Add repo witch ile /etc/apt/sources.list
      shell:  sh -c 'echo deb http://download.proxmox.com/debian/pve buster pvetest >  /etc/apt/sources.list'
    
    - name: Configure file /etc/apt/sources.list # написать
      #deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
      deb http://download.proxmox.com/debian/pve buster pvetest
    
