---
- name: Update and Upgrade 
  hosts: "{{ host }}"
  gather_facts: no
  become: yes  #sudo


  tasks:
    - name: UPDATE (apt update -y)
      apt:
        update_cache: yes
      register: apt_update
    - debug: msg="{{ apt_update }}"

    - name: UPGRADE (apt upgrade -y)
      apt:
        upgrade: 'yes'
      register: apt_upgrade
    - debug: msg="{{ apt_upgrade }}"

    - name: Install packages  
      apt:
        name: '{{ item }}'
        state: latest
      loop:
      - vim
      - mc
      - net-tools
    
