---
# --- Playbook from vault secret
- name: Ansible Vault Secret
  hosts: ub1604
  become: yes  #sudo

  vars:
    adm_passwd: xxx

  tasks:

    - name: Install packeges Tree
      apt: name=tree state=latest

    - name: Create Config File
      copy:
        dest: "/home/myconfig.conf"
        content:
          port: 9092
          log: 7day
          home: /var/log/
          user: root
          password: {{ adm_passwd }}