---
- name: Create AWS EC2 Instance
  hosts: local
  connection: local
  gather_fact: false
  vars:
    keypair: xxxx-key-paris                           # Name of KyePain as written in AWS Console
    Instance_type: t2.micro                           # Type of EC2 Ssever to Create
    image: ami-0fhjdhdj                               # AMI of Server in This Region
    region: us-east-2                                 # Name of Region
    count: 1                                          # How many Servers to Create
    security_group: Ansible-SecurityGroup             # Name of SecurityGroup
    aws_access_key:                                   # Credentials to Create AWS EC2
    aws_secret_key:                                   # Credentials to Create AWS EC2
  
  tasks:
    - name: Create a security grop with Port 22 and 80 to any (0.0.0.0/0)
      ec_group:
        name:         "{{ security_group }}" 
        description:  SecurityGroup of Server with Port 22,80,443 Open
        region:       "{{ region }}"
        rules:
          - proto: tcp
            from_port:   22
            to_port:     22
            cidr_ip:     0.0.0.0/0
          - proto: tcp
            from_port:  80
            to_port:    80
            cidr_ip:    0.0.0.0/0
          - proto: tcp
            from_port:  443
            to_port:    443
            cidr_ip:    0.0.0.0/0
        rules_engress:
          - proto:    all
            cidr_ip:  0.0.0.0/0
        aws_access_key: "{{ aws_access_key }}"                                   # Credentials to Create AWS EC2
        aws_secret_key: "{{ aws_secret_key }}" 
    
    - name: Create New AWS EC2 Server
      ec2: 
        key_name:       "{{ keypair }}"
        instance_type:  "{{ instance_type }}"
        image:          "{{ image }}"
        group:          "{{ security_group }}"
        region:         "{{ region }}"
        Instance_tags:
          Name:         AnsibleDeploynent
          Type:         AnsibleEC2-WS
        count:          "{{ count }}"
        wait:           true
        aws_access_key: "{{ aws_access_key }}"                                   # Credentials to Create AWS EC2
        aws_secret_key: "{{ aws_secret_key }}"
      register:         ec2                                                      # Start Creation of AWS EC2 Server

    - name: Print all ec2 variables
      debug: var=ec2
        
