---
# -- Provision SUSE ---
- name: Provison SUSE Server 
  hosts: suse
  become: true
  vars_files:
    - vars_vault.yml

  roles:
    - role: common
    #- role: nginx
    #- role: common
    #- role: php
    #- role: common
    #- role: geerlingguy.mysql
    #- role: common
    #- role: mysql-prepare
    - role: wp
